// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinates.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace RPCDemoClient {
  public static partial class CoordinateService
  {
    static readonly string __ServiceName = "multiplied_coordinates.CoordinateService";

    static readonly grpc::Marshaller<global::RPCDemoClient.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RPCDemoClient.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RPCDemoClient.Coordinates> __Marshaller_Coordinates = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RPCDemoClient.Coordinates.Parser.ParseFrom);

    static readonly grpc::Method<global::RPCDemoClient.Empty, global::RPCDemoClient.Coordinates> __Method_GetCoordinates = new grpc::Method<global::RPCDemoClient.Empty, global::RPCDemoClient.Coordinates>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCoordinates",
        __Marshaller_Empty,
        __Marshaller_Coordinates);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RPCDemoClient.CoordinatesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CoordinateService</summary>
    public abstract partial class CoordinateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::RPCDemoClient.Coordinates> GetCoordinates(global::RPCDemoClient.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CoordinateService</summary>
    public partial class CoordinateServiceClient : grpc::ClientBase<CoordinateServiceClient>
    {
      /// <summary>Creates a new client for CoordinateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CoordinateServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CoordinateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CoordinateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CoordinateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CoordinateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::RPCDemoClient.Coordinates GetCoordinates(global::RPCDemoClient.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCoordinates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RPCDemoClient.Coordinates GetCoordinates(global::RPCDemoClient.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCoordinates, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RPCDemoClient.Coordinates> GetCoordinatesAsync(global::RPCDemoClient.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCoordinatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RPCDemoClient.Coordinates> GetCoordinatesAsync(global::RPCDemoClient.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCoordinates, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CoordinateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CoordinateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CoordinateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCoordinates, serviceImpl.GetCoordinates).Build();
    }

  }
}
#endregion
