# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinates.proto\x12\x16multiplied_coordinates\"\x07\n\x05\x45mpty\"3\n\x0b\x43oordinates\x12\n\n\x02\x63x\x18\x01 \x01(\x02\x12\n\n\x02\x63y\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x03 \x01(\x02\x32k\n\x11\x43oordinateService\x12V\n\x0eGetCoordinates\x12\x1d.multiplied_coordinates.Empty\x1a#.multiplied_coordinates.Coordinates\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=45
  _EMPTY._serialized_end=52
  _COORDINATES._serialized_start=54
  _COORDINATES._serialized_end=105
  _COORDINATESERVICE._serialized_start=107
  _COORDINATESERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
