M4-Mid Term | Bryan Marquez: RPCDemoClient.CoordinateService.CoordinateServiceClient Class Reference
RPCDemoClient.CoordinateService.CoordinateServiceClient Class Reference
Client for CoordinateService.
Public Member Functions
CoordinateServiceClient (grpc::Channel channel)
Creates a new client for CoordinateService.
CoordinateServiceClient (grpc::CallInvoker callInvoker)
Creates a new client for CoordinateService that uses a custom CallInvoker.
virtual global::RPCDemoClient.Coordinates GetCoordinates (global::RPCDemoClient.Empty request, grpc::Metadata headers=null, DateTime? deadline=null, CancellationToken cancellationToken=default(CancellationToken))
virtual global::RPCDemoClient.Coordinates GetCoordinates (global::RPCDemoClient.Empty request, grpc::CallOptions options)
virtual grpc::AsyncUnaryCall< global::RPCDemoClient.Coordinates > GetCoordinatesAsync (global::RPCDemoClient.Empty request, grpc::Metadata headers=null, DateTime? deadline=null, CancellationToken cancellationToken=default(CancellationToken))
virtual grpc::AsyncUnaryCall< global::RPCDemoClient.Coordinates > GetCoordinatesAsync (global::RPCDemoClient.Empty request, grpc::CallOptions options)
Protected Member Functions
CoordinateServiceClient ()
Protected parameterless constructor to allow creation of test doubles.
CoordinateServiceClient (ClientBaseConfiguration configuration)
Protected constructor to allow creation of configured clients.
override CoordinateServiceClient NewInstance (ClientBaseConfiguration configuration)
Creates a new instance of client from given ClientBaseConfiguration.
Detailed Description
Client for CoordinateService.
Definition at line 42 of file CoordinatesGrpc.cs.
Constructor & Destructor Documentation
CoordinateServiceClient() [1/4]
RPCDemoClient.CoordinateService.CoordinateServiceClient.CoordinateServiceClient (grpc::Channel channel) inline
Creates a new client for CoordinateService.
Parameters
channel The channel to use to make remote calls.
Definition at line 46 of file CoordinatesGrpc.cs.
                                                          : base(channel)
      {
      }
CoordinateServiceClient() [2/4]
RPCDemoClient.CoordinateService.CoordinateServiceClient.CoordinateServiceClient (grpc::CallInvoker callInvoker) inline
Creates a new client for CoordinateService that uses a custom CallInvoker.
Parameters
callInvoker The callInvoker to use to make remote calls.
Definition at line 51 of file CoordinatesGrpc.cs.
                                                                  : base(callInvoker)
      {
      }
CoordinateServiceClient() [3/4]
RPCDemoClient.CoordinateService.CoordinateServiceClient.CoordinateServiceClient () inline protected
Protected parameterless constructor to allow creation of test doubles.
Definition at line 55 of file CoordinatesGrpc.cs.
                                          : base()
      {
      }
Referenced by RPCDemoClient.CoordinateService.CoordinateServiceClient.NewInstance().
CoordinateServiceClient() [4/4]
RPCDemoClient.CoordinateService.CoordinateServiceClient.CoordinateServiceClient (ClientBaseConfiguration configuration) inline protected
Protected constructor to allow creation of configured clients.
Parameters
configuration The client configuration.
Definition at line 60 of file CoordinatesGrpc.cs.
                                                                               : base(configuration)
      {
      }
Member Function Documentation
GetCoordinates() [1/2]
virtual global.RPCDemoClient.Coordinates RPCDemoClient.CoordinateService.CoordinateServiceClient.GetCoordinates (global::RPCDemoClient::Empty request, grpc::CallOptions options) inline virtual
Definition at line 68 of file CoordinatesGrpc.cs.
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCoordinates, null, options, request);
      }
Referenced by coordinates_pb2_grpc.CoordinateServiceStub.__init__().
GetCoordinates() [2/2]
virtual global.RPCDemoClient.Coordinates RPCDemoClient.CoordinateService.CoordinateServiceClient.GetCoordinates (global::RPCDemoClient::Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Definition at line 64 of file CoordinatesGrpc.cs.
      {
        return GetCoordinates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
Referenced by coordinates_pb2_grpc.CoordinateServiceStub.__init__().
GetCoordinatesAsync() [1/2]
virtual grpc.AsyncUnaryCall< global.RPCDemoClient.Coordinates > RPCDemoClient.CoordinateService.CoordinateServiceClient.GetCoordinatesAsync (global::RPCDemoClient::Empty request, grpc::CallOptions options) inline virtual
Definition at line 76 of file CoordinatesGrpc.cs.
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCoordinates, null, options, request);
      }
GetCoordinatesAsync() [2/2]
virtual grpc.AsyncUnaryCall< global.RPCDemoClient.Coordinates > RPCDemoClient.CoordinateService.CoordinateServiceClient.GetCoordinatesAsync (global::RPCDemoClient::Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Definition at line 72 of file CoordinatesGrpc.cs.
      {
        return GetCoordinatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
NewInstance()
override CoordinateServiceClient RPCDemoClient.CoordinateService.CoordinateServiceClient.NewInstance (ClientBaseConfiguration configuration) inline protected
Creates a new instance of client from given ClientBaseConfiguration.
Definition at line 81 of file CoordinatesGrpc.cs.
      {
        return new CoordinateServiceClient(configuration);
      }
References RPCDemoClient.CoordinateService.CoordinateServiceClient.CoordinateServiceClient().
The documentation for this class was generated from the following file:
Client_rpc/Client_rpc/protos/CoordinatesGrpc.cs