M4-Mid Term | Bryan Marquez: _setup_util Namespace Reference
_setup_util Namespace Reference
Functions
rollback_env_variables (environ, env_var_subfolders)
_rollback_env_variable (environ, name, subfolders)
_get_workspaces (environ, include_fuerte=False, include_non_existing=False)
prepend_env_variables (environ, env_var_subfolders, workspaces)
_prefix_env_variable (environ, name, paths, subfolders)
assignment (key, value)
comment (msg)
prepend (environ, key, prefix)
find_env_hooks (environ, cmake_prefix_path)
_parse_arguments (args=None)
Variables
str CATKIN_MARKER_FILE = '.catkin'
system = platform.system()
tuple IS_DARWIN = (system == 'Darwin')
tuple IS_WINDOWS = (system == 'Windows')
list PATH_TO_ADD_SUFFIX = ['bin']
dict ENV_VAR_SUBFOLDERS
args = _parse_arguments()
e
file
str CMAKE_PREFIX_PATH = r'/home/bryan/M4-MidTerm/catkin_home/devel;/opt/ros/noetic'.split(';')
base_path = os.path.dirname(__file__)
environ = dict(os.environ)
list lines = []
Detailed Description
This file generates shell code for the setup.SHELL scripts to set environment variables.
Function Documentation
_get_workspaces()
_setup_util._get_workspaces (environ, include_fuerte = False, include_non_existing = False) protected
Based on CMAKE_PREFIX_PATH return all catkin workspaces.
:param include_fuerte: The flag if paths starting with '/opt/ros/fuerte' should be considered workspaces, ``bool``
Definition at line 122 of file _setup_util.py.
def _get_workspaces(environ, include_fuerte=False, include_non_existing=False):
    """
    Based on CMAKE_PREFIX_PATH return all catkin workspaces.
    :param include_fuerte: The flag if paths starting with '/opt/ros/fuerte' should be considered workspaces, ``bool``
    """
    # get all cmake prefix paths
    env_name = 'CMAKE_PREFIX_PATH'
    value = environ[env_name] if env_name in environ else ''
    paths = [path for path in value.split(os.pathsep) if path]
    # remove non-workspace paths
    workspaces = [path for path in paths if os.path.isfile(os.path.join(path, CATKIN_MARKER_FILE)) or (include_fuerte and path.startswith('/opt/ros/fuerte')) or (include_non_existing and not os.path.exists(path))]
    return workspaces
Referenced by _rollback_env_variable().
_parse_arguments()
_setup_util._parse_arguments (args = None) protected
Definition at line 254 of file _setup_util.py.
def _parse_arguments(args=None):
    parser = argparse.ArgumentParser(description='Generates code blocks for the setup.SHELL script.')
    parser.add_argument('--extend', action='store_true', help='Skip unsetting previous environment variables to extend context')
    parser.add_argument('--local', action='store_true', help='Only consider this prefix path and ignore other prefix path in the environment')
    return parser.parse_known_args(args=args)[0]
_prefix_env_variable()
_setup_util._prefix_env_variable (environ, name, paths, subfolders) protected
Return the prefix to prepend to the environment variable NAME.
Adding any path in NEW_PATHS_STR without creating duplicate or empty items.
Definition at line 154 of file _setup_util.py.
def _prefix_env_variable(environ, name, paths, subfolders):
    """
    Return the prefix to prepend to the environment variable NAME.
    Adding any path in NEW_PATHS_STR without creating duplicate or empty items.
    """
    value = environ[name] if name in environ else ''
    environ_paths = [path for path in value.split(os.pathsep) if path]
    checked_paths = []
    for path in paths:
        if not isinstance(subfolders, list):
            subfolders = [subfolders]
        for subfolder in subfolders:
            path_tmp = path
            if subfolder:
                path_tmp = os.path.join(path_tmp, subfolder)
            # skip nonexistent paths
            if not os.path.exists(path_tmp):
                continue
            # exclude any path already in env and any path we already added
            if path_tmp not in environ_paths and path_tmp not in checked_paths:
                checked_paths.append(path_tmp)
    prefix_str = os.pathsep.join(checked_paths)
    if prefix_str != '' and environ_paths:
        prefix_str += os.pathsep
    return prefix_str
Referenced by prepend_env_variables().
_rollback_env_variable()
_setup_util._rollback_env_variable (environ, name, subfolders) protected
For each catkin workspace in CMAKE_PREFIX_PATH remove the first entry from env[NAME] matching workspace + subfolder.
:param subfolders: list of str '' or subfoldername that may start with '/'
:returns: the updated value of the environment variable.
Definition at line 91 of file _setup_util.py.
def _rollback_env_variable(environ, name, subfolders):
    """
    For each catkin workspace in CMAKE_PREFIX_PATH remove the first entry from env[NAME] matching workspace + subfolder.
    :param subfolders: list of str '' or subfoldername that may start with '/'
    :returns: the updated value of the environment variable.
    """
    value = environ[name] if name in environ else ''
    env_paths = [path for path in value.split(os.pathsep) if path]
    value_modified = False
    for subfolder in subfolders:
        if subfolder:
            if subfolder.startswith(os.path.sep) or (os.path.altsep and subfolder.startswith(os.path.altsep)):
                subfolder = subfolder[1:]
            if subfolder.endswith(os.path.sep) or (os.path.altsep and subfolder.endswith(os.path.altsep)):
                subfolder = subfolder[:-1]
        for ws_path in _get_workspaces(environ, include_fuerte=True, include_non_existing=True):
            path_to_find = os.path.join(ws_path, subfolder) if subfolder else ws_path
            path_to_remove = None
            for env_path in env_paths:
                env_path_clean = env_path[:-1] if env_path and env_path[-1] in [os.path.sep, os.path.altsep] else env_path
                if env_path_clean == path_to_find:
                    path_to_remove = env_path
                    break
            if path_to_remove:
                env_paths.remove(path_to_remove)
                value_modified = True
    new_value = os.pathsep.join(env_paths)
    return new_value if value_modified else None
References _get_workspaces().
Referenced by rollback_env_variables().
assignment()
_setup_util.assignment (key, value)
Definition at line 182 of file _setup_util.py.
def assignment(key, value):
    if not IS_WINDOWS:
        return 'export %s="%s"' % (key, value)
    else:
        return 'set %s=%s' % (key, value)
comment()
_setup_util.comment (msg)
Definition at line 189 of file _setup_util.py.
def comment(msg):
    if not IS_WINDOWS:
        return '# %s' % msg
    else:
        return 'REM %s' % msg
find_env_hooks()
_setup_util.find_env_hooks (environ, cmake_prefix_path)
Generate shell code with found environment hooks for the all workspaces.
Definition at line 205 of file _setup_util.py.
def find_env_hooks(environ, cmake_prefix_path):
    """Generate shell code with found environment hooks for the all workspaces."""
    lines = []
    lines.append(comment('found environment hooks in workspaces'))
    generic_env_hooks = []
    generic_env_hooks_workspace = []
    specific_env_hooks = []
    specific_env_hooks_workspace = []
    generic_env_hooks_by_filename = {}
    specific_env_hooks_by_filename = {}
    generic_env_hook_ext = 'bat' if IS_WINDOWS else 'sh'
    specific_env_hook_ext = environ['CATKIN_SHELL'] if not IS_WINDOWS and 'CATKIN_SHELL' in environ and environ['CATKIN_SHELL'] else None
    # remove non-workspace paths
    workspaces = [path for path in cmake_prefix_path.split(os.pathsep) if path and os.path.isfile(os.path.join(path, CATKIN_MARKER_FILE))]
    for workspace in reversed(workspaces):
        env_hook_dir = os.path.join(workspace, 'etc', 'catkin', 'profile.d')
        if os.path.isdir(env_hook_dir):
            for filename in sorted(os.listdir(env_hook_dir)):
                if filename.endswith('.%s' % generic_env_hook_ext):
                    # remove previous env hook with same name if present
                    if filename in generic_env_hooks_by_filename:
                        i = generic_env_hooks.index(generic_env_hooks_by_filename[filename])
                        generic_env_hooks.pop(i)
                        generic_env_hooks_workspace.pop(i)
                    # append env hook
                    generic_env_hooks.append(os.path.join(env_hook_dir, filename))
                    generic_env_hooks_workspace.append(workspace)
                    generic_env_hooks_by_filename[filename] = generic_env_hooks[-1]
                elif specific_env_hook_ext is not None and filename.endswith('.%s' % specific_env_hook_ext):
                    # remove previous env hook with same name if present
                    if filename in specific_env_hooks_by_filename:
                        i = specific_env_hooks.index(specific_env_hooks_by_filename[filename])
                        specific_env_hooks.pop(i)
                        specific_env_hooks_workspace.pop(i)
                    # append env hook
                    specific_env_hooks.append(os.path.join(env_hook_dir, filename))
                    specific_env_hooks_workspace.append(workspace)
                    specific_env_hooks_by_filename[filename] = specific_env_hooks[-1]
    env_hooks = generic_env_hooks + specific_env_hooks
    env_hooks_workspace = generic_env_hooks_workspace + specific_env_hooks_workspace
    count = len(env_hooks)
    lines.append(assignment('_CATKIN_ENVIRONMENT_HOOKS_COUNT', count))
    for i in range(count):
        lines.append(assignment('_CATKIN_ENVIRONMENT_HOOKS_%d' % i, env_hooks[i]))
        lines.append(assignment('_CATKIN_ENVIRONMENT_HOOKS_%d_WORKSPACE' % i, env_hooks_workspace[i]))
    return lines
References find_env_hooks(), prepend_env_variables(), and rollback_env_variables().
Referenced by find_env_hooks().
prepend()
_setup_util.prepend (environ, key, prefix)
Definition at line 196 of file _setup_util.py.
def prepend(environ, key, prefix):
    if key not in environ or not environ[key]:
        return assignment(key, prefix)
    if not IS_WINDOWS:
        return 'export %s="%s$%s"' % (key, prefix, key)
    else:
        return 'set %s=%s%%%s%%' % (key, prefix, key)
prepend_env_variables()
_setup_util.prepend_env_variables (environ, env_var_subfolders, workspaces)
Generate shell code to prepend environment variables for the all workspaces.
Definition at line 137 of file _setup_util.py.
def prepend_env_variables(environ, env_var_subfolders, workspaces):
    """Generate shell code to prepend environment variables for the all workspaces."""
    lines = []
    lines.append(comment('prepend folders of workspaces to environment variables'))
    paths = [path for path in workspaces.split(os.pathsep) if path]
    prefix = _prefix_env_variable(environ, 'CMAKE_PREFIX_PATH', paths, '')
    lines.append(prepend(environ, 'CMAKE_PREFIX_PATH', prefix))
    for key in sorted(key for key in env_var_subfolders.keys() if key != 'CMAKE_PREFIX_PATH'):
        subfolder = env_var_subfolders[key]
        prefix = _prefix_env_variable(environ, key, paths, subfolder)
        lines.append(prepend(environ, key, prefix))
    return lines
References _prefix_env_variable().
Referenced by find_env_hooks().
rollback_env_variables()
_setup_util.rollback_env_variables (environ, env_var_subfolders)
Generate shell code to reset environment variables.
by unrolling modifications based on all workspaces in CMAKE_PREFIX_PATH.
This does not cover modifications performed by environment hooks.
Definition at line 69 of file _setup_util.py.
def rollback_env_variables(environ, env_var_subfolders):
    """
    Generate shell code to reset environment variables.
    by unrolling modifications based on all workspaces in CMAKE_PREFIX_PATH.
    This does not cover modifications performed by environment hooks.
    """
    lines = []
    unmodified_environ = copy.copy(environ)
    for key in sorted(env_var_subfolders.keys()):
        subfolders = env_var_subfolders[key]
        if not isinstance(subfolders, list):
            subfolders = [subfolders]
        value = _rollback_env_variable(unmodified_environ, key, subfolders)
        if value is not None:
            environ[key] = value
            lines.append(assignment(key, value))
    if lines:
        lines.insert(0, comment('reset environment variables by unrolling modifications based on all workspaces in CMAKE_PREFIX_PATH'))
    return lines
References _rollback_env_variable().
Referenced by find_env_hooks().
Variable Documentation
args
_setup_util.args = _parse_arguments()
Definition at line 264 of file _setup_util.py.
base_path
_setup_util.base_path = os.path.dirname(__file__)
Definition at line 276 of file _setup_util.py.
CATKIN_MARKER_FILE
str _setup_util.CATKIN_MARKER_FILE = '.catkin'
Definition at line 47 of file _setup_util.py.
CMAKE_PREFIX_PATH
list _setup_util.CMAKE_PREFIX_PATH = r'/home/bryan/M4-MidTerm/catkin_home/devel;/opt/ros/noetic'.split(';')
Definition at line 271 of file _setup_util.py.
e
_setup_util.e
Definition at line 266 of file _setup_util.py.
ENV_VAR_SUBFOLDERS
dict _setup_util.ENV_VAR_SUBFOLDERS
Initial value:
=  {
    'CMAKE_PREFIX_PATH': '',
    'LD_LIBRARY_PATH' if not IS_DARWIN else 'DYLD_LIBRARY_PATH': ['lib', os.path.join('lib', 'x86_64-linux-gnu')],
    'PATH': PATH_TO_ADD_SUFFIX,
    'PKG_CONFIG_PATH': [os.path.join('lib', 'pkgconfig'), os.path.join('lib', 'x86_64-linux-gnu', 'pkgconfig')],
    'PYTHONPATH': 'lib/python3/dist-packages',
}
Definition at line 60 of file _setup_util.py.
environ
_setup_util.environ = dict(os.environ)
Definition at line 286 of file _setup_util.py.
file
_setup_util.file
Definition at line 266 of file _setup_util.py.
IS_DARWIN
tuple _setup_util.IS_DARWIN = (system == 'Darwin')
Definition at line 50 of file _setup_util.py.
IS_WINDOWS
tuple _setup_util.IS_WINDOWS = (system == 'Windows')
Definition at line 51 of file _setup_util.py.
lines
list _setup_util.lines = []
Definition at line 287 of file _setup_util.py.
PATH_TO_ADD_SUFFIX
list _setup_util.PATH_TO_ADD_SUFFIX = ['bin']
Definition at line 53 of file _setup_util.py.
system
_setup_util.system = platform.system()
Definition at line 49 of file _setup_util.py.